os: linux
language: node_js
dist: xenial

jobs:
  include:
    - language: android
      jdk: oraclejdk8
      env:
        - NODE_VERSION=10.15.3
        - ANDROID_API=28
        - ANDROID_BUILD_TOOLS=28.0.3
      before_cache:
        - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
        - rm -rf $HOME/.gradle/caches/*/plugin-resolution/
      cache:
        directories:
          - $HOME/.yarn-cache
          - $HOME/.gradle/caches/
          - $HOME/.gradle/wrapper/
      android:
        components:
          - tools
          - platform-tools
          - android-${ANDROID_API}
          - build-tools-${ANDROID_BUILD_TOOLS}

      install:
        - nvm install $NODE_VERSION
        - nvm use $NODE_VERSION
        - nvm alias default $NODE_VERSION
        - node --version
        - npm install -g yarn --ignore-dependencies
        - npm install -g react-native-cli
        - cd Example
        - yarn

      script:
        - cd ./android && ./gradlew assembleDebug

    - language: objective-c
      os: osx
      xcode_workspace: './ios/ReanimatedExample.xcworkspace'
      xcode_scheme: ReanimatedExample
      xcode_sdk: iphonesimulator9.0
      osx_image: xcode10.1
      podfile: './ios/Podfile'
      xcode_destination: platform=iOS Simulator,OS=11.4,name=iPhone X
      env: NODE_VERSION=10.15.3

      branches:
        only:
          - master

      cache: yarn

      install:
        - nvm --version
        - echo $NODE_VERSION
        - xcodebuild -version
        - sudo launchctl limit maxfiles 2048 unlimited
        - sudo ulimit -n 10000
        - nvm install $NODE_VERSION
        - nvm use $NODE_VERSION
        - nvm alias default $NODE_VERSION
        - brew install yarn --ignore-dependencies
        - npm install -g react-native-cli
        - cd Example
        - yarn
        - cd ios && pod install && cd ..

      script:
        - xcodebuild -workspace ./ios/ReanimatedExample.xcworkspace -scheme ReanimatedExample -configuration Debug -sdk iphonesimulator -derivedDataPath ./ios/build -quiet |  egrep '^(/.+:[0-9+:[0-9]+:.error:|fatal|===)' || [[ $? == 1 ]] | uniq && exit ${PIPESTATUS[0]}

    - language: node_js
      node_js:
        - 10
      cache:
        directories:
          - node_modules
      script:
        - yarn
        - yarn test
