name: Validate iOS

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/validate-ios.yml'
      - 'ios/**'
  pull_request:
    paths:
      - '.github/workflows/validate-ios.yml'
      - 'ios/**'

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Check imports
        run: ./scripts/validate-ios.sh
